[workspace]
members = [
  "packages/transformers/js/core",
  "packages/transformers/js/napi",
  "packages/transformers/js/wasm",
  "packages/utils/fs-search",
]

[profile.release]
opt-level = 3
# lto = true
